// this file is automatically generated by running `python autogen.py`
#include "../qk_int_sv_f8_cuda_sm89.cuh"
template void SpargeAttentionSM89Dispatched<128, 64, 32, 64, 64, 2, float, true, true, 1, nv_bfloat16, true, true, false>(
  int8_t* Q, int8_t* K, __nv_fp8_e4m3* V, nv_bfloat16* O,
  int32_t* PV_Count, int32_t *__restrict__ Lut, int32_t *__restrict__ Valid_Block_Num, float *__restrict__ PV_Threshold,
  float* Q_scale, float* K_scale, float* V_scale,
  const uint32_t batch_size, const uint32_t qo_len, const uint32_t kv_len, const uint32_t num_qo_heads, const uint32_t num_kv_heads,
  const uint32_t stride_bz_q, const uint32_t stride_seq_q, const uint32_t stride_h_q,
  const uint32_t stride_bz_k, const uint32_t stride_seq_k, const uint32_t stride_h_k,
  const uint32_t stride_bz_v, const uint32_t stride_h_v, const uint32_t stride_d_v,
  const uint32_t stride_bz_o, const uint32_t stride_seq_o, const uint32_t stride_h_o,
  float sm_scale
);
