# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%y%m%d}_${now:%H%M%S}_${hydra.job.override_dirname}
sweep:
  dir: ${paths.log_dir}/${task_name}/multi/${now:%y%m%d}_${now:%H%M%S}
#  subdir: ${hydra.job.num}
#  subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  subdir: ${hydra.job.num}_${now:%y%m%d}_${now:%H%M%S}
